{"metadata":{"modules":[{"name":"Authentication"}],"role":"symbol","symbolKind":"case","title":"OAuthProviderError.invalidResponse","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidResponse","kind":"identifier"}],"externalID":"s:14Authentication18OAuthProviderErrorO15invalidResponseyA2CmF"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/authentication\/oauthprovidererror\/invalidresponse"]}],"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"abstract":[{"text":"The authorization request received an invalid response.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidResponse","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"role":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"text":"A type that indicates when OAuth operartion encounters an error.","type":"text"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/invalidResponse":{"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/invalidresponse","role":"symbol","type":"topic","abstract":[{"text":"The authorization request received an invalid response.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidResponse"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse","title":"OAuthProviderError.invalidResponse"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","type":"topic","url":"\/documentation\/authentication","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication"}}}