{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/authentication\/oauthprovidererror\/invalidresponse"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The authorization request received an invalid response."}],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"sections":[],"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"OAuthProviderError.invalidResponse","modules":[{"name":"Authentication"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidResponse","kind":"identifier"}],"externalID":"s:14Authentication18OAuthProviderErrorO15invalidResponseyA2CmF"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidResponse","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse"},"kind":"symbol","references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","url":"\/documentation\/authentication","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","role":"collection","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/invalidResponse":{"title":"OAuthProviderError.invalidResponse","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidResponse"}],"abstract":[{"text":"The authorization request received an invalid response.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse","kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/invalidresponse"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","role":"symbol"}}}