{"abstract":[{"text":"The private key data provided was invalid.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidPrivateKeyData"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fido2\/publickeycredentialerror\/invalidprivatekeydata"]}],"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"PublicKeyCredentialError.invalidPrivateKeyData","role":"symbol","externalID":"s:5FIDO224PublicKeyCredentialErrorO014invalidPrivateC4DatayA2CmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidPrivateKeyData"}],"modules":[{"name":"FIDO2"}],"roleHeading":"Case"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidPrivateKeyData":{"url":"\/documentation\/fido2\/publickeycredentialerror\/invalidprivatekeydata","title":"PublicKeyCredentialError.invalidPrivateKeyData","role":"symbol","abstract":[{"type":"text","text":"The private key data provided was invalid."}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidPrivateKeyData","kind":"identifier"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"type":"topic","role":"collection","kind":"symbol","title":"FIDO2","url":"\/documentation\/fido2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","abstract":[]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"url":"\/documentation\/fido2\/publickeycredentialerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"kind":"symbol"}}}