{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidAttestationData","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"Authentication data or client data hash is invalid.","type":"text"}],"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"PublicKeyCredentialError.invalidAttestationData","modules":[{"name":"FIDO2"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAttestationData"}],"externalID":"s:5FIDO224PublicKeyCredentialErrorO22invalidAttestationDatayA2CmF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"variants":[{"paths":["\/documentation\/fido2\/publickeycredentialerror\/invalidattestationdata"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"url":"\/documentation\/fido2\/publickeycredentialerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"type":"topic","role":"collection","kind":"symbol","title":"FIDO2","url":"\/documentation\/fido2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","abstract":[]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidAttestationData":{"kind":"symbol","abstract":[{"type":"text","text":"Authentication data or client data hash is invalid."}],"title":"PublicKeyCredentialError.invalidAttestationData","role":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidattestationdata","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAttestationData"}]}}}