{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/failureReason","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/helpAnchor","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/recoverySuggestion"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"FIDO2"}]},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/failureReason":{"url":"\/documentation\/fido2\/publickeycredentialerror\/failurereason","abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/failureReason","title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/fido2","title":"FIDO2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","type":"topic","url":"\/documentation\/fido2\/publickeycredentialerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"role":"symbol","navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/helpAnchor":{"title":"helpAnchor","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/helpAnchor","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/fido2\/publickeycredentialerror\/helpanchor"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/recoverySuggestion":{"url":"\/documentation\/fido2\/publickeycredentialerror\/recoverysuggestion","abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/recoverySuggestion","title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"}}}