{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unableToCreateSignature","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unable to create a signature based on the private key and attestation data."}],"kind":"symbol","variants":[{"paths":["\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"FIDO2"}],"externalID":"s:5FIDO224PublicKeyCredentialErrorO23unableToCreateSignatureyA2CmF","symbolKind":"case","roleHeading":"Case","title":"PublicKeyCredentialError.unableToCreateSignature","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unableToCreateSignature","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"role":"collection","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/fido2","title":"FIDO2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","type":"topic","url":"\/documentation\/fido2\/publickeycredentialerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"role":"symbol","navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateSignature":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","role":"symbol","title":"PublicKeyCredentialError.unableToCreateSignature","abstract":[{"text":"Unable to create a signature based on the private key and attestation data.","type":"text"}],"url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unableToCreateSignature","kind":"identifier"}]}}}