{"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"FIDO2"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unableToCreateKey"}],"title":"PublicKeyCredentialError.unableToCreateKey","externalID":"s:5FIDO224PublicKeyCredentialErrorO014unableToCreateC0yA2CmF","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unableToCreateKey","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A private key could not be created from the the private key data."}],"variants":[{"paths":["\/documentation\/fido2\/publickeycredentialerror\/unabletocreatekey"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateKey":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","title":"PublicKeyCredentialError.unableToCreateKey","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unableToCreateKey"}],"abstract":[{"type":"text","text":"A private key could not be created from the the private key data."}],"url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatekey"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"type":"topic","role":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror","abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}],"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","url":"\/documentation\/fido2","title":"FIDO2","kind":"symbol","role":"collection","type":"topic"}}}