{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unableToCreateSignature","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Unable to create a signature based on the private key and attestation data."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError"]]},"metadata":{"modules":[{"name":"FIDO2"}],"title":"PublicKeyCredentialError.unableToCreateSignature","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unableToCreateSignature"}],"roleHeading":"Case","externalID":"s:5FIDO224PublicKeyCredentialErrorO23unableToCreateSignatureyA2CmF"},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"type":"topic","role":"collection","kind":"symbol","title":"FIDO2","url":"\/documentation\/fido2","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","abstract":[]},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"url":"\/documentation\/fido2\/publickeycredentialerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PublicKeyCredentialError"}],"kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateSignature":{"kind":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature","title":"PublicKeyCredentialError.unableToCreateSignature","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","role":"symbol","abstract":[{"type":"text","text":"Unable to create a signature based on the private key and attestation data."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unableToCreateSignature"}],"type":"topic"}}}