{"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError\/transportFailed(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error occured establishing the networking connection."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/core\/urlsessionerror\/transportfailed(_:)"]}],"kind":"symbol","metadata":{"title":"URLSessionError.transportFailed(_:)","symbolKind":"case","modules":[{"name":"Core"}],"role":"symbol","roleHeading":"Case","externalID":"s:4Core15URLSessionErrorO15transportFailedyACs0C0_pcACmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"transportFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transportFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/Core/URLSessionError/transportFailed(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transportFailed"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An error occured establishing the networking connection."}],"url":"\/documentation\/core\/urlsessionerror\/transportfailed(_:)","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError\/transportFailed(_:)","title":"URLSessionError.transportFailed(_:)"},"doc://com.ibm.verify.ios.sdk/documentation/Core/URLSessionError":{"kind":"symbol","url":"\/documentation\/core\/urlsessionerror","abstract":[{"type":"text","text":"An error that occurs during URLSession operations."}],"navigatorTitle":[{"kind":"identifier","text":"URLSessionError"}],"title":"URLSessionError","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core\/URLSessionError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"URLSessionError","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/documentation/Core":{"title":"Core","kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Core","url":"\/documentation\/core","role":"collection","abstract":[],"type":"topic"}}}