{"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","doc:\/\/com.ibm.verify.ios.sdk\/SQ","doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"metadata":{"roleHeading":"Enumeration","title":"PublicKeyCredentialError","symbolKind":"enum","modules":[{"name":"FIDO2"}],"navigatorTitle":[{"kind":"identifier","text":"PublicKeyCredentialError"}],"externalID":"s:5FIDO224PublicKeyCredentialErrorO","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicKeyCredentialError"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2"]]},"sections":[],"variants":[{"paths":["\/documentation\/fido2\/publickeycredentialerror"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"A type that indicates when Fido2ApiClient encounters an error."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","interfaceLanguage":"swift"},"references":{"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidCertificate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidCertificate","title":"PublicKeyCredentialError.invalidCertificate","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCertificate"}],"abstract":[{"text":"The certifcate could not be parsed.","type":"text"}],"url":"\/documentation\/fido2\/publickeycredentialerror\/invalidcertificate","kind":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateKey":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateKey","title":"PublicKeyCredentialError.unableToCreateKey","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unableToCreateKey"}],"abstract":[{"type":"text","text":"A private key could not be created from the the private key data."}],"url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatekey"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidAttestationData":{"url":"\/documentation\/fido2\/publickeycredentialerror\/invalidattestationdata","kind":"symbol","title":"PublicKeyCredentialError.invalidAttestationData","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidAttestationData","kind":"identifier"}],"abstract":[{"text":"Authentication data or client data hash is invalid.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidAttestationData"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Equatable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/fido2\/publickeycredentialerror\/equatable-implementations","kind":"article"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/invalidPrivateKeyData":{"type":"topic","title":"PublicKeyCredentialError.invalidPrivateKeyData","abstract":[{"type":"text","text":"The private key data provided was invalid."}],"role":"symbol","kind":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror\/invalidprivatekeydata","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidPrivateKeyData","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/invalidPrivateKeyData"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/timeout":{"url":"\/documentation\/fido2\/publickeycredentialerror\/timeout","kind":"symbol","title":"PublicKeyCredentialError.timeout","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"abstract":[{"text":"The time allocated to complete the operation has expired.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/timeout"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError":{"type":"topic","role":"symbol","url":"\/documentation\/fido2\/publickeycredentialerror","abstract":[{"text":"A type that indicates when Fido2ApiClient encounters an error.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError","title":"PublicKeyCredentialError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PublicKeyCredentialError","kind":"identifier"}],"navigatorTitle":[{"text":"PublicKeyCredentialError","kind":"identifier"}]},"doc://com.ibm.verify.ios.sdk/SQ":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/Error-Implementations":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/Error-Implementations","title":"Error Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/fido2\/publickeycredentialerror\/error-implementations","abstract":[],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/errorDescription":{"url":"\/documentation\/fido2\/publickeycredentialerror\/errordescription","kind":"symbol","title":"errorDescription","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/errorDescription"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/LocalizedError-Implementations":{"url":"\/documentation\/fido2\/publickeycredentialerror\/localizederror-implementations","title":"LocalizedError Implementations","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/LocalizedError-Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2":{"abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2","url":"\/documentation\/fido2","title":"FIDO2","kind":"symbol","role":"collection","type":"topic"},"doc://com.ibm.verify.ios.sdk/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"},"doc://com.ibm.verify.ios.sdk/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/unableToCreateSignature":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unableToCreateSignature","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/unableToCreateSignature","abstract":[{"text":"Unable to create a signature based on the private key and attestation data.","type":"text"}],"kind":"symbol","title":"PublicKeyCredentialError.unableToCreateSignature","url":"\/documentation\/fido2\/publickeycredentialerror\/unabletocreatesignature"},"doc://com.ibm.verify.ios.sdk/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","type":"unresolvable","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP"},"doc://com.ibm.verify.ios.sdk/documentation/FIDO2/PublicKeyCredentialError/general(message:)":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/FIDO2\/PublicKeyCredentialError\/general(message:)","url":"\/documentation\/fido2\/publickeycredentialerror\/general(message:)","role":"symbol","title":"PublicKeyCredentialError.general(message:)","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"general","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"General error with custom message.","type":"text"}]}}}